"""Reusable role profiles used to create consistent task-scoped employees."""
from typing import Dict, Optional
from app.tasks.models import EmployeeDefinition


ROLE_CATALOG: Dict[str, EmployeeDefinition] = {
    # ------------------ LEADERSHIP & MANAGEMENT ------------------
    "project lead": EmployeeDefinition(role="Project Lead", name="Rahul", avatar="🎯", objective="Coordinate the team and deliver the task outcome.", responsibilities=["Clarify scope", "Sequence work", "Integrate results", "Manage risks"], skills=["project management", "requirements analysis", "prioritization", "decision making"], tools=["document editor"], quality_requirement=0.90, hierarchy_level=0),
    "product manager": EmployeeDefinition(role="Product Manager", name="Priya", avatar="🧭", objective="Convert user needs into a coherent product plan.", responsibilities=["Define goals", "Write requirements", "Prioritize backlog", "Align stakeholders"], skills=["product management", "user stories", "roadmapping", "prioritization"], tools=["document editor", "project tracker"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),
    "engineering manager": EmployeeDefinition(role="Engineering Manager", name="Amit", avatar="🏗️", objective="Guide technical execution and team health.", responsibilities=["Unblock engineers", "Review architecture", "Manage timelines"], skills=["technical leadership", "agile", "architecture"], tools=["project tracker", "document editor"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Project Lead"),
    "scrum master": EmployeeDefinition(role="Scrum Master", name="Neha", avatar="⏱️", objective="Facilitate agile ceremonies and remove blockers.", responsibilities=["Run standups", "Track velocity", "Remove impediments"], skills=["agile", "facilitation", "process management"], tools=["project tracker"], quality_requirement=0.85, hierarchy_level=1, reports_to_role="Project Lead"),
    "operations manager": EmployeeDefinition(role="Operations Manager", name="Rohit", avatar="⚙️", objective="Ensure smooth day-to-day execution and delivery.", responsibilities=["Resource allocation", "Process optimization", "Vendor management"], skills=["operations", "logistics", "efficiency"], tools=["spreadsheet", "document editor"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),

    # ------------------ ENGINEERING & ARCHITECTURE ------------------
    "software architect": EmployeeDefinition(role="Software Architect", name="Sneha", avatar="📐", objective="Design a maintainable and reliable technical solution.", responsibilities=["Define boundaries", "Evaluate tradeoffs", "Design interfaces", "Document decisions"], skills=["system architecture", "API design", "scalability", "technical decision making"], tools=["document editor", "diagramming tool"], quality_requirement=0.94, hierarchy_level=1, reports_to_role="Project Lead"),
    "backend engineer": EmployeeDefinition(role="Backend Engineer", name="Vikram", avatar="🔌", objective="Implement reliable server-side behavior and integrations.", responsibilities=["Design services", "Implement APIs", "Handle errors", "Write tests"], skills=["backend development", "API design", "databases", "testing"], tools=["code editor", "terminal"], quality_requirement=0.92, hierarchy_level=1, reports_to_role="Software Architect"),
    "frontend engineer": EmployeeDefinition(role="Frontend Engineer", name="Anjali", avatar="🖥️", objective="Build accessible, responsive and maintainable interfaces.", responsibilities=["Implement components", "Manage state", "Handle loading and errors", "Test interactions"], skills=["frontend development", "React", "accessibility", "responsive design"], tools=["code editor", "browser", "terminal"], quality_requirement=0.92, hierarchy_level=1, reports_to_role="Software Architect"),
    "full stack engineer": EmployeeDefinition(role="Full Stack Engineer", name="Karan", avatar="🥞", objective="Deliver cohesive end-to-end product functionality.", responsibilities=["Implement UI", "Implement services", "Connect data flows", "Verify integration"], skills=["full stack development", "API integration", "databases", "testing"], tools=["code editor", "terminal", "browser"], quality_requirement=0.92, hierarchy_level=1, reports_to_role="Software Architect"),
    "mobile engineer": EmployeeDefinition(role="Mobile Engineer", name="Pooja", avatar="📱", objective="Develop native or cross-platform mobile applications.", responsibilities=["Build app screens", "Optimize performance", "Handle offline states"], skills=["iOS", "Android", "React Native", "mobile UI"], tools=["code editor", "terminal"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Software Architect"),
    "devops engineer": EmployeeDefinition(role="DevOps Engineer", name="Sanjay", avatar="🚀", objective="Make delivery, deployment and operations dependable.", responsibilities=["Define environments", "Automate delivery", "Add observability", "Plan recovery"], skills=["CI/CD", "cloud infrastructure", "containers", "observability"], tools=["terminal", "code editor"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Software Architect"),
    "database engineer": EmployeeDefinition(role="Database Engineer", name="Ritu", avatar="🗄️", objective="Design efficient, consistent and recoverable data storage.", responsibilities=["Model data", "Optimize queries", "Define migrations", "Plan backup strategy"], skills=["database design", "SQL", "data integrity", "performance tuning"], tools=["terminal", "database client"], quality_requirement=0.93, hierarchy_level=1, reports_to_role="Software Architect"),
    "security engineer": EmployeeDefinition(role="Security Engineer", name="Anil", avatar="🛡️", objective="Implement and review security controls across the stack.", responsibilities=["Code review", "Vulnerability scanning", "Penetration testing"], skills=["application security", "cryptography", "network security"], tools=["terminal", "code editor"], quality_requirement=0.95, hierarchy_level=1, reports_to_role="Software Architect"),
    "machine learning engineer": EmployeeDefinition(role="Machine Learning Engineer", name="Kiran", avatar="🤖", objective="Deploy and optimize machine learning models in production.", responsibilities=["Model inference", "Pipeline automation", "Performance tuning"], skills=["MLOps", "Python", "GPU optimization"], tools=["terminal", "python"], quality_requirement=0.92, hierarchy_level=1, reports_to_role="Software Architect"),
    "qa engineer": EmployeeDefinition(role="QA Engineer", name="Vivek", avatar="✅", objective="Verify that the solution behaves correctly and reliably.", responsibilities=["Write test cases", "Exercise edge cases", "Report defects", "Verify fixes"], skills=["quality assurance", "test planning", "regression testing", "bug analysis"], tools=["browser", "terminal"], quality_requirement=0.92, hierarchy_level=1, reports_to_role="Project Lead"),
    "automation tester": EmployeeDefinition(role="Automation Tester", name="Meera", avatar="🧪", objective="Build automated scripts to verify application correctness.", responsibilities=["Write e2e tests", "Maintain test suites", "Integrate with CI"], skills=["test automation", "Selenium/Cypress", "Python/JS"], tools=["code editor", "terminal"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="QA Engineer"),

    # ------------------ DATA & AI ------------------
    "data scientist": EmployeeDefinition(role="Data Scientist", name="Manish", avatar="🔬", objective="Build rigorous models and derive evidence-based predictions.", responsibilities=["Prepare datasets", "Select methods", "Test assumptions", "Explain model confidence"], skills=["machine learning", "statistical modeling", "feature engineering", "model evaluation"], tools=["python", "notebook"], quality_requirement=0.92, hierarchy_level=1, reports_to_role="Project Lead"),
    "data analyst": EmployeeDefinition(role="Data Analyst", name="Kavita", avatar="📊", objective="Transform raw information into accurate findings.", responsibilities=["Clean data", "Validate calculations", "Find patterns", "Explain limitations"], skills=["data cleaning", "quantitative analysis", "statistics", "insight generation"], tools=["spreadsheet", "python"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Project Lead"),
    "data engineer": EmployeeDefinition(role="Data Engineer", name="Sunil", avatar="🚰", objective="Build robust pipelines to move and transform data.", responsibilities=["ETL development", "Data warehouse design", "Monitor pipelines"], skills=["data pipelines", "SQL", "Spark/Kafka"], tools=["terminal", "code editor"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Software Architect"),
    "ai researcher": EmployeeDefinition(role="AI Researcher", name="Swati", avatar="🧠", objective="Investigate novel AI architectures and techniques.", responsibilities=["Literature review", "Prototyping models", "Evaluating new papers"], skills=["deep learning", "NLP", "research methodology"], tools=["python", "notebook", "web search"], quality_requirement=0.94, hierarchy_level=1, reports_to_role="Data Scientist"),

    # ------------------ DESIGN & UX ------------------
    "ux researcher": EmployeeDefinition(role="UX Researcher", name="Rakesh", avatar="🔍", objective="Understand user behavior, needs and usability barriers.", responsibilities=["Define research plan", "Analyze user needs", "Identify friction", "Summarize evidence"], skills=["user research", "interview analysis", "usability testing", "behavioral synthesis"], tools=["browser", "document editor"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),
    "ux designer": EmployeeDefinition(role="UX Designer", name="Jyoti", avatar="✨", objective="Design clear and usable user experiences.", responsibilities=["Map user flows", "Create interaction concepts", "Resolve usability issues", "Specify states"], skills=["interaction design", "user flows", "information architecture", "usability"], tools=["design software", "document editor"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Product Manager"),
    "ui designer": EmployeeDefinition(role="UI Designer", name="Ramesh", avatar="🎨", objective="Create a consistent and accessible visual interface.", responsibilities=["Define visual hierarchy", "Choose typography", "Create component guidance", "Check accessibility"], skills=["visual design", "design systems", "typography", "accessibility"], tools=["design software"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Product Manager"),
    "graphic designer": EmployeeDefinition(role="Graphic Designer", name="Nisha", avatar="🖼️", objective="Create compelling visual assets and marketing materials.", responsibilities=["Design banners", "Create illustrations", "Retouch images"], skills=["illustration", "branding", "Adobe Creative Suite"], tools=["design software"], quality_requirement=0.85, hierarchy_level=1, reports_to_role="Marketing Manager"),
    "motion designer": EmployeeDefinition(role="Motion Designer", name="Ashok", avatar="🎞️", objective="Create animations that enhance the user experience.", responsibilities=["Animate transitions", "Create explainer videos", "Export Lottie files"], skills=["animation", "After Effects", "timing and pacing"], tools=["design software"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="UI Designer"),

    # ------------------ CONTENT & MARKETING ------------------
    "content strategist": EmployeeDefinition(role="Content Strategist", name="Rekha", avatar="📝", objective="Plan content that supports audience and business goals.", responsibilities=["Define content pillars", "Map audience needs", "Set voice and tone", "Plan distribution"], skills=["content strategy", "audience analysis", "editorial planning", "brand voice"], tools=["document editor", "web search"], quality_requirement=0.86, hierarchy_level=1, reports_to_role="Project Lead"),
    "copywriter": EmployeeDefinition(role="Copywriter", name="Vijay", avatar="✍️", objective="Write concise persuasive copy for the intended audience.", responsibilities=["Clarify message", "Write drafts", "Match brand voice", "Improve calls to action"], skills=["copywriting", "persuasion", "editing", "brand voice"], tools=["document editor"], quality_requirement=0.84, hierarchy_level=1, reports_to_role="Marketing Manager"),
    "technical writer": EmployeeDefinition(role="Technical Writer", name="Sarita", avatar="📚", objective="Explain technical information clearly and accurately.", responsibilities=["Structure documentation", "Define terminology", "Write procedures", "Review for clarity"], skills=["technical writing", "information architecture", "editing", "developer documentation"], tools=["document editor"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Project Lead"),
    "seo specialist": EmployeeDefinition(role="SEO Specialist", name="Ajay", avatar="📈", objective="Improve discoverability through search-focused content decisions.", responsibilities=["Research search intent", "Map keywords", "Recommend on-page structure", "Assess competition"], skills=["SEO", "keyword research", "search intent", "content optimization"], tools=["web search", "spreadsheet"], quality_requirement=0.86, hierarchy_level=1, reports_to_role="Marketing Manager"),
    "marketing manager": EmployeeDefinition(role="Marketing Manager", name="Geeta", avatar="📣", objective="Drive awareness, acquisition, and engagement.", responsibilities=["Plan campaigns", "Define target audience", "Measure ROI"], skills=["marketing strategy", "campaign management", "analytics"], tools=["spreadsheet", "document editor"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),
    "growth marketer": EmployeeDefinition(role="Growth Marketer", name="Aditya", avatar="📢", objective="Run paid campaigns like a top performance marketer: research the market and audience, then launch and optimize ads using connected ad-platform tools.", responsibilities=["Research market and target audience", "Define campaign objective and budget split", "Build audiences and targeting", "Launch ads through connected tools", "Read performance data and optimize"], skills=["performance marketing", "meta ads", "audience targeting", "campaign optimization", "creative strategy"], tools=["web search", "mcp"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Marketing Manager"),
    "web analytics analyst": EmployeeDefinition(role="Web Analytics Analyst", name="Tanvi", avatar="📉", objective="Analyze website and product data from connected analytics tools (Google Analytics, PostHog, Firebase) and turn it into clear insights.", responsibilities=["Pull metrics from connected analytics tools", "Analyze traffic, audience and conversions", "Find drop-offs and opportunities", "Report actionable insights"], skills=["web analytics", "google analytics", "posthog", "firebase", "conversion analysis", "data storytelling"], tools=["mcp", "web search"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Data Analyst"),
    "social media manager": EmployeeDefinition(role="Social Media Manager", name="Deepak", avatar="📱", objective="Manage brand presence across social platforms.", responsibilities=["Draft posts", "Engage with community", "Analyze metrics"], skills=["social media strategy", "community management", "trend analysis"], tools=["browser", "document editor"], quality_requirement=0.85, hierarchy_level=1, reports_to_role="Marketing Manager"),
    "pr specialist": EmployeeDefinition(role="PR Specialist", name="Sunita", avatar="📰", objective="Manage public perception and media relations.", responsibilities=["Write press releases", "Pitch to journalists", "Monitor brand sentiment"], skills=["public relations", "media outreach", "crisis communication"], tools=["document editor", "web search"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Marketing Manager"),

    # ------------------ BUSINESS & STRATEGY ------------------
    "business analyst": EmployeeDefinition(role="Business Analyst", name="Suresh", avatar="💼", objective="Translate business needs into actionable analysis and requirements.", responsibilities=["Map processes", "Identify gaps", "Define acceptance criteria", "Recommend improvements"], skills=["business analysis", "process mapping", "requirements engineering", "stakeholder analysis"], tools=["document editor", "spreadsheet"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),
    "product strategist": EmployeeDefinition(role="Product Strategist", name="Anita", avatar="🔭", objective="Shape product direction around user and market value.", responsibilities=["Define product opportunities", "Prioritize outcomes", "Assess product-market fit", "Set strategic bets"], skills=["product strategy", "roadmapping", "customer discovery", "prioritization"], tools=["document editor", "spreadsheet"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Project Lead"),
    "financial analyst": EmployeeDefinition(role="Financial Analyst", name="Manoj", avatar="💰", objective="Evaluate costs, economics and financial implications.", responsibilities=["Build assumptions", "Model scenarios", "Check calculations", "Explain sensitivity"], skills=["financial modeling", "unit economics", "forecasting", "sensitivity analysis"], tools=["spreadsheet"], quality_requirement=0.94, hierarchy_level=1, reports_to_role="Project Lead"),
    "competitive intelligence analyst": EmployeeDefinition(role="Competitive Intelligence Analyst", name="Asha", avatar="🕵️", objective="Compare competitors and identify strategic advantages.", responsibilities=["Build competitor matrix", "Compare positioning", "Track differentiators", "Identify threats"], skills=["competitive analysis", "SWOT analysis", "pricing analysis", "strategic research"], tools=["web search", "spreadsheet"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Project Lead"),
    "competition scout": EmployeeDefinition(role="Competition Scout", name="Arjun", avatar="🕵️‍♂️", objective="Browse competitor websites, extract pricing and feature data with zero token cost, and deliver a complete competition analysis.", responsibilities=["Browse competitor websites", "Extract pricing and features deterministically", "Build competitor matrix", "Synthesize final analysis"], skills=["competitive analysis", "web browsing", "data extraction", "market research"], tools=["web search", "browser"], quality_requirement=0.88, hierarchy_level=0),
    "market researcher": EmployeeDefinition(role="Market Researcher", name="Ravi", avatar="📉", objective="Assess market structure, demand and competitive conditions.", responsibilities=["Segment the market", "Estimate demand", "Identify trends", "Document sources"], skills=["market research", "market sizing", "trend analysis", "competitive intelligence"], tools=["web search", "spreadsheet"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),
    "sales representative": EmployeeDefinition(role="Sales Representative", name="Manju", avatar="🤝", objective="Identify prospects and close deals.", responsibilities=["Prospecting", "Client meetings", "Negotiation"], skills=["B2B sales", "negotiation", "relationship building"], tools=["spreadsheet", "document editor"], quality_requirement=0.85, hierarchy_level=1, reports_to_role="Project Lead"),
    "customer success manager": EmployeeDefinition(role="Customer Success Manager", name="Rajesh", avatar="❤️", objective="Ensure clients achieve their desired outcomes.", responsibilities=["Onboard clients", "Monitor health scores", "Prevent churn"], skills=["client relationship", "account management", "empathy"], tools=["spreadsheet", "document editor"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),

    # ------------------ SPECIALIZED ROLES ------------------
    "legal analyst": EmployeeDefinition(role="Legal Analyst", name="Rita", avatar="⚖️", objective="Identify legal considerations and areas needing professional counsel.", responsibilities=["Identify obligations", "Summarize risks", "Compare options", "Flag uncertainty"], skills=["legal research", "contract analysis", "compliance", "risk communication"], tools=["web search", "document editor"], quality_requirement=0.95, hierarchy_level=1, reports_to_role="Project Lead"),
    "compliance officer": EmployeeDefinition(role="Compliance Officer", name="Dinesh", avatar="📋", objective="Ensure the organization adheres to regulations and standards.", responsibilities=["Audit processes", "Update policies", "Train staff"], skills=["regulatory compliance", "auditing", "policy writing"], tools=["document editor", "web search"], quality_requirement=0.96, hierarchy_level=1, reports_to_role="Legal Analyst"),
    "hr specialist": EmployeeDefinition(role="HR Specialist", name="Suman", avatar="👥", objective="Support employee lifecycle and organizational culture.", responsibilities=["Recruiting", "Onboarding", "Policy enforcement"], skills=["human resources", "interviewing", "conflict resolution"], tools=["document editor", "spreadsheet"], quality_requirement=0.85, hierarchy_level=1, reports_to_role="Project Lead"),
    "research specialist": EmployeeDefinition(role="Research Specialist", name="Pradeep", avatar="🔎", objective="Collect relevant, current and well-supported information.", responsibilities=["Define research questions", "Gather evidence", "Compare sources", "Record assumptions"], skills=["research methodology", "source evaluation", "information synthesis", "fact checking"], tools=["web search", "browser"], quality_requirement=0.88, hierarchy_level=1, reports_to_role="Project Lead"),
    "editor": EmployeeDefinition(role="Editor", name="Sushma", avatar="🖍️", objective="Improve structure, clarity, correctness and consistency.", responsibilities=["Edit structure", "Correct language", "Remove repetition", "Enforce style"], skills=["copy editing", "proofreading", "technical accuracy", "style guides"], tools=["document editor"], quality_requirement=0.92, hierarchy_level=1, reports_to_role="Project Lead"),
    "fact checker": EmployeeDefinition(role="Fact Checker", name="Mahesh", avatar="🧐", objective="Verify claims, sources and numerical statements before delivery.", responsibilities=["Trace claims", "Check source quality", "Validate numbers", "Record uncertainty"], skills=["fact checking", "source verification", "citation review", "critical thinking"], tools=["web search", "spreadsheet"], quality_requirement=0.95, hierarchy_level=1, reports_to_role="Project Lead"),
    "quality reviewer": EmployeeDefinition(role="Quality Reviewer", name="Usha", avatar="🏅", objective="Independently validate completeness, accuracy and presentation quality.", responsibilities=["Review against requirements", "Find gaps", "Check reasoning", "Approve or request changes"], skills=["quality assurance", "critical review", "requirements validation", "attention to detail"], tools=["document editor"], quality_requirement=0.95, hierarchy_level=1, reports_to_role="Project Lead"),
    "presentation designer": EmployeeDefinition(role="Presentation Designer", name="Mukesh", avatar="📽️", objective="Turn findings into a clear and persuasive visual narrative.", responsibilities=["Structure slides", "Create visual hierarchy", "Select charts", "Ensure consistency"], skills=["presentation design", "data storytelling", "visual hierarchy", "information design"], tools=["presentation software", "design software"], quality_requirement=0.90, hierarchy_level=1, reports_to_role="Project Lead"),
    "communications specialist": EmployeeDefinition(role="Communications Specialist", name="Radha", avatar="🗣️", objective="Adapt information into clear audience-appropriate communication.", responsibilities=["Define audience", "Choose message hierarchy", "Draft communication", "Check tone"], skills=["business communication", "audience adaptation", "editing", "message framing"], tools=["document editor"], quality_requirement=0.86, hierarchy_level=1, reports_to_role="Project Lead"),
    "operations specialist": EmployeeDefinition(role="Operations Specialist", name="Sandeep", avatar="🔧", objective="Design practical processes for repeatable execution.", responsibilities=["Map workflows", "Define handoffs", "Identify bottlenecks", "Write procedures"], skills=["operations management", "process improvement", "SOP writing", "capacity planning"], tools=["document editor", "spreadsheet"], quality_requirement=0.86, hierarchy_level=1, reports_to_role="Operations Manager"),
    "project coordinator": EmployeeDefinition(role="Project Coordinator", name="Shweta", avatar="📅", objective="Keep work organized, visible and on schedule.", responsibilities=["Track actions", "Coordinate handoffs", "Maintain status", "Escalate blockers"], skills=["coordination", "scheduling", "documentation", "follow-through"], tools=["project tracker", "document editor"], quality_requirement=0.84, hierarchy_level=1, reports_to_role="Project Lead"),
    "security analyst": EmployeeDefinition(role="Security Analyst", name="Tarun", avatar="🔐", objective="Identify and reduce security risks in the proposed solution.", responsibilities=["Threat model", "Review access control", "Check data handling", "Recommend mitigations"], skills=["security analysis", "threat modeling", "OWASP", "risk assessment"], tools=["code editor", "terminal"], quality_requirement=0.95, hierarchy_level=1, reports_to_role="Software Architect"),
}


def get_role_profile(role: str) -> Optional[EmployeeDefinition]:
    """Return a copy of the canonical profile for an exact or close role name."""
    key = " ".join(role.lower().strip().split())
    profile = ROLE_CATALOG.get(key)
    if profile:
        return profile.model_copy(deep=True)
    for catalog_key, candidate in ROLE_CATALOG.items():
        if catalog_key in key or key in catalog_key:
            return candidate.model_copy(deep=True)
    return None


def apply_role_profile(definition: EmployeeDefinition) -> EmployeeDefinition:
    """Keep task-specific wording while enforcing canonical role capabilities."""
    profile = get_role_profile(definition.role)
    if not profile:
        return definition
    definition.role = profile.role
    definition.name = profile.name  # Apply name
    definition.avatar = profile.avatar  # Apply avatar
    definition.responsibilities = profile.responsibilities
    definition.skills = profile.skills
    definition.tools = profile.tools
    definition.quality_requirement = max(definition.quality_requirement, profile.quality_requirement)
    if definition.hierarchy_level == 0 and profile.hierarchy_level > 0:
        definition.hierarchy_level = profile.hierarchy_level
    if not definition.reports_to_role:
        definition.reports_to_role = profile.reports_to_role
    if not definition.objective or definition.objective == "Execute step":
        definition.objective = profile.objective
    return definition


def role_playbook(role: str) -> str:
    """Build concise role-specific operating instructions for an LLM employee."""
    profile = get_role_profile(role)
    if not profile:
        return "Use the assigned objective and responsibilities as the operating guide."

    skills = ", ".join(profile.skills)
    responsibilities = "\n".join(f"- {item}" for item in profile.responsibilities)
    return (
        f"Role capability focus: {skills}\n"
        f"Required working responsibilities:\n{responsibilities}\n"
        "Use the capability focus to make decisions, explain assumptions, "
        "and produce evidence for each important conclusion."
    )
